/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import Dao.AuditDAO;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Klein
 */
public class IfrAudit extends javax.swing.JInternalFrame {

    AuditDAO auditDAO = new AuditDAO();
    int codigo = 0;
    private static IfrAudit tela;
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
    Date dataIni = null;
    Date dataFim = null;

    /**
     * Creates new form IfrMaterial
     */
    public IfrAudit() {
        this.setTitle("Auditoria");
        initComponents();
        dataInicial();

        //auditDAO.popularTabela2(tblEmail, "email", "usuario");
        auditDAO.popEmail(tblEmail);
        auditDAO.popTabela(tblTabela);
        auditDAO.popAcao(tblAcao);
        
        //Formatacao.formatarData(tffDataInicial);
        //Formatacao.formatarData(tffDataFinal);
        //Formatacao.limparjtable(tblAuditoria);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")


    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAuditoria = new javax.swing.JTable();
        btnPesquisar = new javax.swing.JButton();
        btnfechar1 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblEmail = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        tblTabela = new javax.swing.JTable();
        jScrollPane4 = new javax.swing.JScrollPane();
        tblAcao = new javax.swing.JTable();
        btnLimparSelecoes = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        tffDataInicial = new javax.swing.JFormattedTextField();
        jLabel4 = new javax.swing.JLabel();
        tffDataFinal = new javax.swing.JFormattedTextField();

        setTitle("Consulta Formulação");

        tblAuditoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblAuditoria);

        btnPesquisar.setText("Pesquisar");
        btnPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPesquisarActionPerformed(evt);
            }
        });

        btnfechar1.setText("Fechar");
        btnfechar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnfechar1ActionPerformed(evt);
            }
        });

        tblEmail.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Título 2"
            }
        ));
        jScrollPane2.setViewportView(tblEmail);
        if (tblEmail.getColumnModel().getColumnCount() > 0) {
            tblEmail.getColumnModel().getColumn(0).setPreferredWidth(5);
        }

        tblTabela.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Título 2"
            }
        ));
        jScrollPane3.setViewportView(tblTabela);

        tblAcao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Título 2"
            }
        ));
        jScrollPane4.setViewportView(tblAcao);

        btnLimparSelecoes.setText("Limpar Seleções");
        btnLimparSelecoes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparSelecoesActionPerformed(evt);
            }
        });

        jLabel3.setText("Data Inicial Período:");

        jLabel4.setText("Data Final Período:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnPesquisar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnfechar1, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(52, 52, 52)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(53, 53, 53)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 771, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(btnLimparSelecoes)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addGap(2, 2, 2)
                            .addComponent(tffDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel4)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tffDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tffDataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tffDataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 199, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnLimparSelecoes)
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnPesquisar)
                    .addComponent(btnfechar1))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void dataInicial() {
        try {
            dataIni = sdf.parse("01/01/0001");
            dataFim = sdf.parse("01/01/5000");
        } catch (Exception e) {
            System.out.println("Erro: " + e);
        }
    }


    private void btnPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPesquisarActionPerformed
        DefaultTableModel modelEmail = (DefaultTableModel) tblEmail.getModel();
        DefaultTableModel modelAcao = (DefaultTableModel) tblAcao.getModel();
        DefaultTableModel modelTabela = (DefaultTableModel) tblTabela.getModel();
        String selectedEmail = null;
        String selectedAcao = null;
        String selectedTabela = null;


        if (tblEmail.getSelectedRow() == -1) {
            selectedEmail = "";
        } else {
            selectedEmail = String.valueOf(modelEmail.getValueAt(tblEmail.getSelectedRow(), 1));
        }
        if (tblTabela.getSelectedRow() == -1) {
            selectedTabela = "";
        } else {
            selectedTabela = String.valueOf(modelTabela.getValueAt(tblTabela.getSelectedRow(), 2));
        }
        if (tblAcao.getSelectedRow() == -1) {
            selectedAcao = "";
        } else {
            selectedAcao = String.valueOf(modelAcao.getValueAt(tblAcao.getSelectedRow(), 4));
        }
        try {
//            if (tffDataInicial.getText().equals("  /  /    ") && tffDataFinal.getText().equals("  /  /    ")) {
//               auditDAO.popularTabela(tblAuditoria, selectedEmail, selectedTabela, selectedAcao, dataIni, dataFim);
//            } else {

                //java.sql.Date data = new java.sql.Date(sdf.parse(tffDataInicial.getText()).getTime());
                //java.sql.Date data2 = new java.sql.Date(sdf.parse(tffDataFinal.getText()).getTime());
            auditDAO.popularTabela(tblAuditoria, selectedEmail , selectedTabela, selectedAcao);//, data, data2);
            //}
        } catch (Exception e) {
            System.out.println("Erro: " + e);
        }


    }//GEN-LAST:event_btnPesquisarActionPerformed

    private void btnfechar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnfechar1ActionPerformed
        dispose();
    }//GEN-LAST:event_btnfechar1ActionPerformed

    private void btnLimparSelecoesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparSelecoesActionPerformed
        tblEmail.getSelectionModel().clearSelection();
        tblTabela.getSelectionModel().clearSelection();
        tblAcao.getSelectionModel().clearSelection();
        tffDataInicial.setText("");
        tffDataFinal.setText("");

    }//GEN-LAST:event_btnLimparSelecoesActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLimparSelecoes;
    private javax.swing.JButton btnPesquisar;
    private javax.swing.JButton btnfechar1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tblAcao;
    private javax.swing.JTable tblAuditoria;
    private javax.swing.JTable tblEmail;
    private javax.swing.JTable tblTabela;
    private javax.swing.JFormattedTextField tffDataFinal;
    private javax.swing.JFormattedTextField tffDataInicial;
    // End of variables declaration//GEN-END:variables
}
