/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Tela;

import Dao.ReportDAO;
import Util.Formatacao;
import com.toedter.calendar.JDateChooser;
import com.toedter.calendar.JTextFieldDateEditor;
import java.awt.Color;
import java.awt.Component;
import java.io.File;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JComponent;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author klein
 */
public class IfrRelLoginData extends javax.swing.JInternalFrame {

    /**
     * Creates new form IfrMaterial
     */
    
    private static IfrRelLoginData instance;
    
    public IfrRelLoginData() {
        initComponents();
        desabilitarEdicaoJDC(jDateChooserIni);
        desabilitarEdicaoJDC(jDateChooserFim);
    }
    
    public static IfrRelLoginData getInstance() {
        if (instance == null) {
            instance = new IfrRelLoginData();
        }
        return instance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")

    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnGerar = new javax.swing.JButton();
        btnFechar = new javax.swing.JButton();
        jDateChooserIni = new com.toedter.calendar.JDateChooser();
        jDateChooserFim = new com.toedter.calendar.JDateChooser();

        setTitle("Relatório");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Login por Data");

        jLabel4.setText("Data Inicial:");

        jLabel5.setText("Data Final:");

        btnGerar.setText("Gerar");
        btnGerar.setMaximumSize(new java.awt.Dimension(65, 23));
        btnGerar.setMinimumSize(new java.awt.Dimension(65, 23));
        btnGerar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerarActionPerformed(evt);
            }
        });

        btnFechar.setText("Fechar");
        btnFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFecharActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(100, 100, 100)
                        .addComponent(btnGerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnFechar)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(49, 49, 49))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jDateChooserIni, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDateChooserFim, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(58, 58, 58))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDateChooserIni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooserFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnFechar)
                    .addComponent(btnGerar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        getAccessibleContext().setAccessibleName("Formulações por Data");

        setBounds(0, 0, 365, 196);
    }// </editor-fold>//GEN-END:initComponents

    public static void desabilitarEdicaoJDC(JDateChooser j) {
        JTextFieldDateEditor editor = (JTextFieldDateEditor) j.getDateEditor();
        editor.setEditable(false);
    }

    public static void jdcAmarelo(JDateChooser j) {
        for (Component c : j.getComponents()) {
            ((JComponent) c).setBackground(Color.YELLOW);
        }
    }

    public static void jdcBranco(JDateChooser j) {
        for (Component c : j.getComponents()) {
            ((JComponent) c).setBackground(Color.WHITE);
        }
    }

    private void btnGerarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerarActionPerformed
        if (Formatacao.JcalendarNull(jDateChooserIni) && !Formatacao.JcalendarNull(jDateChooserFim)) {
            JOptionPane.showMessageDialog(null, "A data inicial deve ser informada!");
            jdcAmarelo(jDateChooserIni);
            jdcBranco(jDateChooserFim);
            jDateChooserIni.requestFocusInWindow();
        } else if ((!Formatacao.JcalendarNull(jDateChooserIni) && Formatacao.JcalendarNull(jDateChooserFim))) {
            JOptionPane.showMessageDialog(null, "A data final deve ser informada!");
            jdcAmarelo(jDateChooserFim);
            jdcBranco(jDateChooserIni);
            jDateChooserFim.requestFocusInWindow();
        } else if (Formatacao.JcalendarNull(jDateChooserIni) && Formatacao.JcalendarNull(jDateChooserFim)) {
            JOptionPane.showMessageDialog(null, "Nenhuma data foi informada!");
            jdcAmarelo(jDateChooserIni);
            jdcAmarelo(jDateChooserFim);
        } else if (jDateChooserIni.getCalendar().after(jDateChooserFim.getCalendar())) {
            JOptionPane.showMessageDialog(null, "A data inicial é posterior a data final!");
            jdcAmarelo(jDateChooserIni);
            jdcAmarelo(jDateChooserFim);
        } else {
            jdcBranco(jDateChooserIni);
            jdcBranco(jDateChooserFim);

            new Thread() {
                @Override
                public void run() {
                    try {
                        SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yy");
                        Date dteIni = sdf.parse(Formatacao.formatarJcaledar(jDateChooserIni));
                        Date dteFim = sdf.parse(Formatacao.formatarJcaledar(jDateChooserFim));

                        // Compila o relatorio
                        File target = new java.io.File("RelatorioLoginData.jrxml");
                        JasperReport relatorio = JasperCompileManager.compileReport(target.toString());

                        Map parametros = new HashMap();

                        // adiciona parametros
                        parametros.put("dataIni", dteIni);
                        parametros.put("dataFim", dteFim);

                        // Executa relatoio
                        JasperPrint impressao = JasperFillManager.fillReport(relatorio, parametros, ReportDAO.getInstance().getConnection());

                        // Exibe resultado em video
                        JasperViewer.viewReport(impressao, false);

                    } catch (Exception e) {
                        System.out.println("Erro ao gerar relatório: " + e);
                    }
                }
            }.start();
            dispose();
            instance = null;
        }
    }//GEN-LAST:event_btnGerarActionPerformed

    private void btnFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFecharActionPerformed
        this.dispose();
        instance = null;
    }//GEN-LAST:event_btnFecharActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFechar;
    private javax.swing.JButton btnGerar;
    private com.toedter.calendar.JDateChooser jDateChooserFim;
    private com.toedter.calendar.JDateChooser jDateChooserIni;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    // End of variables declaration//GEN-END:variables
}
